namespace CampusNex
{
    partial class Student
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Student));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.eventsBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.societiesBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.StudentPages = new Bunifu.UI.WinForms.BunifuPages();
            this.SocietiesPage = new System.Windows.Forms.TabPage();
            this.rSocietyForm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.societyCardsPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.userName = new Bunifu.UI.WinForms.BunifuLabel();
            this.userPic = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.searchBar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EventsPage = new System.Windows.Forms.TabPage();
            this.societyReg = new System.Windows.Forms.TabPage();
            this.uploadImageBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.uploadImgPicBox = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.availableMentors = new Bunifu.UI.WinForms.BunifuDropdown();
            this.societyDesc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.societySlogan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.societyName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.regNewSociety = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.sName = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.StudentPages.SuspendLayout();
            this.SocietiesPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.userPic)).BeginInit();
            this.societyReg.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uploadImgPicBox)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.eventsBtn);
            this.panel1.Controls.Add(this.societiesBtn);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(271, 729);
            this.panel1.TabIndex = 0;
            // 
            // eventsBtn
            // 
            this.eventsBtn.AllowAnimations = true;
            this.eventsBtn.AllowMouseEffects = true;
            this.eventsBtn.AllowToggling = true;
            this.eventsBtn.AnimationSpeed = 200;
            this.eventsBtn.AutoGenerateColors = false;
            this.eventsBtn.AutoRoundBorders = false;
            this.eventsBtn.AutoSizeLeftIcon = true;
            this.eventsBtn.AutoSizeRightIcon = true;
            this.eventsBtn.BackColor = System.Drawing.Color.Transparent;
            this.eventsBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.eventsBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("eventsBtn.BackgroundImage")));
            this.eventsBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.eventsBtn.ButtonText = "Events";
            this.eventsBtn.ButtonTextMarginLeft = 0;
            this.eventsBtn.ColorContrastOnClick = 45;
            this.eventsBtn.ColorContrastOnHover = 45;
            this.eventsBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.eventsBtn.CustomizableEdges = borderEdges1;
            this.eventsBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.eventsBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.eventsBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.eventsBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.eventsBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.eventsBtn.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.eventsBtn.ForeColor = System.Drawing.Color.White;
            this.eventsBtn.IconLeft = null;
            this.eventsBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.eventsBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.eventsBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.eventsBtn.IconMarginLeft = 11;
            this.eventsBtn.IconPadding = 10;
            this.eventsBtn.IconRight = null;
            this.eventsBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.eventsBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.eventsBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.eventsBtn.IconSize = 25;
            this.eventsBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.eventsBtn.IdleBorderRadius = 0;
            this.eventsBtn.IdleBorderThickness = 0;
            this.eventsBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.eventsBtn.IdleIconLeftImage = null;
            this.eventsBtn.IdleIconRightImage = null;
            this.eventsBtn.IndicateFocus = true;
            this.eventsBtn.Location = new System.Drawing.Point(27, 234);
            this.eventsBtn.Margin = new System.Windows.Forms.Padding(5);
            this.eventsBtn.Name = "eventsBtn";
            this.eventsBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.eventsBtn.OnDisabledState.BorderRadius = 39;
            this.eventsBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.eventsBtn.OnDisabledState.BorderThickness = 1;
            this.eventsBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.eventsBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.eventsBtn.OnDisabledState.IconLeftImage = null;
            this.eventsBtn.OnDisabledState.IconRightImage = null;
            this.eventsBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.eventsBtn.onHoverState.BorderRadius = 39;
            this.eventsBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.eventsBtn.onHoverState.BorderThickness = 1;
            this.eventsBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.eventsBtn.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.eventsBtn.onHoverState.IconLeftImage = null;
            this.eventsBtn.onHoverState.IconRightImage = null;
            this.eventsBtn.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.eventsBtn.OnIdleState.BorderRadius = 39;
            this.eventsBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.eventsBtn.OnIdleState.BorderThickness = 1;
            this.eventsBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.eventsBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.eventsBtn.OnIdleState.IconLeftImage = null;
            this.eventsBtn.OnIdleState.IconRightImage = null;
            this.eventsBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.eventsBtn.OnPressedState.BorderRadius = 39;
            this.eventsBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.eventsBtn.OnPressedState.BorderThickness = 1;
            this.eventsBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.eventsBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.eventsBtn.OnPressedState.IconLeftImage = null;
            this.eventsBtn.OnPressedState.IconRightImage = null;
            this.eventsBtn.Size = new System.Drawing.Size(220, 50);
            this.eventsBtn.TabIndex = 3;
            this.eventsBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.eventsBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.eventsBtn.TextMarginLeft = 0;
            this.eventsBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.eventsBtn.UseDefaultRadiusAndThickness = true;
            this.eventsBtn.Click += new System.EventHandler(this.societiesBtn_Click);
            // 
            // societiesBtn
            // 
            this.societiesBtn.AllowAnimations = true;
            this.societiesBtn.AllowMouseEffects = true;
            this.societiesBtn.AllowToggling = true;
            this.societiesBtn.AnimationSpeed = 200;
            this.societiesBtn.AutoGenerateColors = false;
            this.societiesBtn.AutoRoundBorders = false;
            this.societiesBtn.AutoSizeLeftIcon = true;
            this.societiesBtn.AutoSizeRightIcon = true;
            this.societiesBtn.BackColor = System.Drawing.Color.Transparent;
            this.societiesBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.societiesBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("societiesBtn.BackgroundImage")));
            this.societiesBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.societiesBtn.ButtonText = "Societies";
            this.societiesBtn.ButtonTextMarginLeft = 0;
            this.societiesBtn.ColorContrastOnClick = 45;
            this.societiesBtn.ColorContrastOnHover = 45;
            this.societiesBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.societiesBtn.CustomizableEdges = borderEdges2;
            this.societiesBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.societiesBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.societiesBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.societiesBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.societiesBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.societiesBtn.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.societiesBtn.ForeColor = System.Drawing.Color.White;
            this.societiesBtn.IconLeft = null;
            this.societiesBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.societiesBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.societiesBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.societiesBtn.IconMarginLeft = 11;
            this.societiesBtn.IconPadding = 10;
            this.societiesBtn.IconRight = null;
            this.societiesBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.societiesBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.societiesBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.societiesBtn.IconSize = 25;
            this.societiesBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.societiesBtn.IdleBorderRadius = 0;
            this.societiesBtn.IdleBorderThickness = 0;
            this.societiesBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.societiesBtn.IdleIconLeftImage = null;
            this.societiesBtn.IdleIconRightImage = null;
            this.societiesBtn.IndicateFocus = true;
            this.societiesBtn.Location = new System.Drawing.Point(27, 155);
            this.societiesBtn.Margin = new System.Windows.Forms.Padding(5);
            this.societiesBtn.Name = "societiesBtn";
            this.societiesBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.societiesBtn.OnDisabledState.BorderRadius = 39;
            this.societiesBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.societiesBtn.OnDisabledState.BorderThickness = 1;
            this.societiesBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.societiesBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.societiesBtn.OnDisabledState.IconLeftImage = null;
            this.societiesBtn.OnDisabledState.IconRightImage = null;
            this.societiesBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.societiesBtn.onHoverState.BorderRadius = 39;
            this.societiesBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.societiesBtn.onHoverState.BorderThickness = 1;
            this.societiesBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.societiesBtn.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.societiesBtn.onHoverState.IconLeftImage = null;
            this.societiesBtn.onHoverState.IconRightImage = null;
            this.societiesBtn.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.societiesBtn.OnIdleState.BorderRadius = 39;
            this.societiesBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.societiesBtn.OnIdleState.BorderThickness = 1;
            this.societiesBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.societiesBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.societiesBtn.OnIdleState.IconLeftImage = null;
            this.societiesBtn.OnIdleState.IconRightImage = null;
            this.societiesBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.societiesBtn.OnPressedState.BorderRadius = 39;
            this.societiesBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.societiesBtn.OnPressedState.BorderThickness = 1;
            this.societiesBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.societiesBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.societiesBtn.OnPressedState.IconLeftImage = null;
            this.societiesBtn.OnPressedState.IconRightImage = null;
            this.societiesBtn.Size = new System.Drawing.Size(220, 50);
            this.societiesBtn.TabIndex = 2;
            this.societiesBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.societiesBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.societiesBtn.TextMarginLeft = 0;
            this.societiesBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.societiesBtn.UseDefaultRadiusAndThickness = true;
            this.societiesBtn.Click += new System.EventHandler(this.societiesBtn_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(82)))), ((int)(((byte)(90)))));
            this.label1.Location = new System.Drawing.Point(109, 56);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(154, 29);
            this.label1.TabIndex = 1;
            this.label1.Text = "CampusNex";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::CampusNex.Properties.Resources.CampusNex1;
            this.pictureBox1.Location = new System.Drawing.Point(-66, -30);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(253, 208);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // StudentPages
            // 
            this.StudentPages.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.StudentPages.AllowTransitions = false;
            this.StudentPages.Controls.Add(this.SocietiesPage);
            this.StudentPages.Controls.Add(this.EventsPage);
            this.StudentPages.Controls.Add(this.societyReg);
            this.StudentPages.Dock = System.Windows.Forms.DockStyle.Fill;
            this.StudentPages.Location = new System.Drawing.Point(271, 0);
            this.StudentPages.Multiline = true;
            this.StudentPages.Name = "StudentPages";
            this.StudentPages.Page = this.societyReg;
            this.StudentPages.PageIndex = 2;
            this.StudentPages.PageName = "societyReg";
            this.StudentPages.PageTitle = "Register a New Society !!";
            this.StudentPages.SelectedIndex = 0;
            this.StudentPages.Size = new System.Drawing.Size(1079, 729);
            this.StudentPages.TabIndex = 1;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.StudentPages.Transition = animation1;
            this.StudentPages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // SocietiesPage
            // 
            this.SocietiesPage.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.SocietiesPage.Controls.Add(this.rSocietyForm);
            this.SocietiesPage.Controls.Add(this.societyCardsPanel);
            this.SocietiesPage.Controls.Add(this.userName);
            this.SocietiesPage.Controls.Add(this.userPic);
            this.SocietiesPage.Controls.Add(this.searchBar);
            this.SocietiesPage.Location = new System.Drawing.Point(4, 4);
            this.SocietiesPage.Name = "SocietiesPage";
            this.SocietiesPage.Padding = new System.Windows.Forms.Padding(3);
            this.SocietiesPage.Size = new System.Drawing.Size(1071, 703);
            this.SocietiesPage.TabIndex = 0;
            this.SocietiesPage.Text = "Societies";
            // 
            // rSocietyForm
            // 
            this.rSocietyForm.AllowAnimations = true;
            this.rSocietyForm.AllowMouseEffects = true;
            this.rSocietyForm.AllowToggling = true;
            this.rSocietyForm.AnimationSpeed = 200;
            this.rSocietyForm.AutoGenerateColors = false;
            this.rSocietyForm.AutoRoundBorders = false;
            this.rSocietyForm.AutoSizeLeftIcon = true;
            this.rSocietyForm.AutoSizeRightIcon = true;
            this.rSocietyForm.BackColor = System.Drawing.Color.Transparent;
            this.rSocietyForm.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.rSocietyForm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rSocietyForm.BackgroundImage")));
            this.rSocietyForm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rSocietyForm.ButtonText = "Register a New Society !!";
            this.rSocietyForm.ButtonTextMarginLeft = 0;
            this.rSocietyForm.ColorContrastOnClick = 45;
            this.rSocietyForm.ColorContrastOnHover = 45;
            this.rSocietyForm.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.rSocietyForm.CustomizableEdges = borderEdges3;
            this.rSocietyForm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.rSocietyForm.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rSocietyForm.DisabledFillColor = System.Drawing.Color.Empty;
            this.rSocietyForm.DisabledForecolor = System.Drawing.Color.Empty;
            this.rSocietyForm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.rSocietyForm.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rSocietyForm.ForeColor = System.Drawing.Color.White;
            this.rSocietyForm.IconLeft = null;
            this.rSocietyForm.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rSocietyForm.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.rSocietyForm.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.rSocietyForm.IconMarginLeft = 11;
            this.rSocietyForm.IconPadding = 10;
            this.rSocietyForm.IconRight = null;
            this.rSocietyForm.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.rSocietyForm.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.rSocietyForm.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.rSocietyForm.IconSize = 25;
            this.rSocietyForm.IdleBorderColor = System.Drawing.Color.Empty;
            this.rSocietyForm.IdleBorderRadius = 0;
            this.rSocietyForm.IdleBorderThickness = 0;
            this.rSocietyForm.IdleFillColor = System.Drawing.Color.Empty;
            this.rSocietyForm.IdleIconLeftImage = null;
            this.rSocietyForm.IdleIconRightImage = null;
            this.rSocietyForm.IndicateFocus = true;
            this.rSocietyForm.Location = new System.Drawing.Point(398, 633);
            this.rSocietyForm.Margin = new System.Windows.Forms.Padding(5);
            this.rSocietyForm.Name = "rSocietyForm";
            this.rSocietyForm.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rSocietyForm.OnDisabledState.BorderRadius = 39;
            this.rSocietyForm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rSocietyForm.OnDisabledState.BorderThickness = 1;
            this.rSocietyForm.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rSocietyForm.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.rSocietyForm.OnDisabledState.IconLeftImage = null;
            this.rSocietyForm.OnDisabledState.IconRightImage = null;
            this.rSocietyForm.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.rSocietyForm.onHoverState.BorderRadius = 39;
            this.rSocietyForm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.rSocietyForm.onHoverState.BorderThickness = 1;
            this.rSocietyForm.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.rSocietyForm.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.rSocietyForm.onHoverState.IconLeftImage = null;
            this.rSocietyForm.onHoverState.IconRightImage = null;
            this.rSocietyForm.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.rSocietyForm.OnIdleState.BorderRadius = 39;
            this.rSocietyForm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rSocietyForm.OnIdleState.BorderThickness = 1;
            this.rSocietyForm.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.rSocietyForm.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.rSocietyForm.OnIdleState.IconLeftImage = null;
            this.rSocietyForm.OnIdleState.IconRightImage = null;
            this.rSocietyForm.OnPressedState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.rSocietyForm.OnPressedState.BorderRadius = 39;
            this.rSocietyForm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rSocietyForm.OnPressedState.BorderThickness = 1;
            this.rSocietyForm.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.rSocietyForm.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.rSocietyForm.OnPressedState.IconLeftImage = null;
            this.rSocietyForm.OnPressedState.IconRightImage = null;
            this.rSocietyForm.Size = new System.Drawing.Size(332, 50);
            this.rSocietyForm.TabIndex = 5;
            this.rSocietyForm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.rSocietyForm.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.rSocietyForm.TextMarginLeft = 0;
            this.rSocietyForm.TextPadding = new System.Windows.Forms.Padding(0);
            this.rSocietyForm.UseDefaultRadiusAndThickness = true;
            this.rSocietyForm.Click += new System.EventHandler(this.rSocietyForm_Click);
            // 
            // societyCardsPanel
            // 
            this.societyCardsPanel.AutoScroll = true;
            this.societyCardsPanel.BackColor = System.Drawing.Color.Transparent;
            this.societyCardsPanel.Location = new System.Drawing.Point(25, 126);
            this.societyCardsPanel.Margin = new System.Windows.Forms.Padding(10);
            this.societyCardsPanel.Name = "societyCardsPanel";
            this.societyCardsPanel.Padding = new System.Windows.Forms.Padding(40, 10, 10, 10);
            this.societyCardsPanel.Size = new System.Drawing.Size(996, 492);
            this.societyCardsPanel.TabIndex = 4;
            // 
            // userName
            // 
            this.userName.AllowParentOverrides = false;
            this.userName.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.userName.AutoEllipsis = false;
            this.userName.Cursor = System.Windows.Forms.Cursors.Default;
            this.userName.CursorType = System.Windows.Forms.Cursors.Default;
            this.userName.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.userName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.userName.Location = new System.Drawing.Point(878, 66);
            this.userName.Name = "userName";
            this.userName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.userName.Size = new System.Drawing.Size(97, 18);
            this.userName.TabIndex = 3;
            this.userName.Text = "User Name";
            this.userName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.userName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // userPic
            // 
            this.userPic.AllowFocused = false;
            this.userPic.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.userPic.AutoSizeHeight = true;
            this.userPic.BorderRadius = 50;
            this.userPic.Image = ((System.Drawing.Image)(resources.GetObject("userPic.Image")));
            this.userPic.IsCircle = true;
            this.userPic.Location = new System.Drawing.Point(781, 22);
            this.userPic.Name = "userPic";
            this.userPic.Size = new System.Drawing.Size(100, 100);
            this.userPic.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.userPic.TabIndex = 2;
            this.userPic.TabStop = false;
            this.userPic.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // searchBar
            // 
            this.searchBar.AcceptsReturn = false;
            this.searchBar.AcceptsTab = false;
            this.searchBar.AnimationSpeed = 200;
            this.searchBar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchBar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchBar.AutoSizeHeight = true;
            this.searchBar.BackColor = System.Drawing.Color.Transparent;
            this.searchBar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchBar.BackgroundImage")));
            this.searchBar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.searchBar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchBar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchBar.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchBar.BorderRadius = 30;
            this.searchBar.BorderThickness = 1;
            this.searchBar.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.searchBar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchBar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchBar.DefaultFont = new System.Drawing.Font("Verdana", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.searchBar.DefaultText = "";
            this.searchBar.FillColor = System.Drawing.Color.LightGray;
            this.searchBar.HideSelection = true;
            this.searchBar.IconLeft = null;
            this.searchBar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchBar.IconPadding = 10;
            this.searchBar.IconRight = global::CampusNex.Properties.Resources.searchIcon;
            this.searchBar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchBar.Lines = new string[0];
            this.searchBar.Location = new System.Drawing.Point(69, 52);
            this.searchBar.MaxLength = 32767;
            this.searchBar.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchBar.Modified = false;
            this.searchBar.Multiline = false;
            this.searchBar.Name = "searchBar";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchBar.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchBar.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchBar.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.LightGray;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Transparent;
            this.searchBar.OnIdleState = stateProperties4;
            this.searchBar.Padding = new System.Windows.Forms.Padding(3);
            this.searchBar.PasswordChar = '\0';
            this.searchBar.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.searchBar.PlaceholderText = "Search Societies";
            this.searchBar.ReadOnly = false;
            this.searchBar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchBar.SelectedText = "";
            this.searchBar.SelectionLength = 0;
            this.searchBar.SelectionStart = 0;
            this.searchBar.ShortcutsEnabled = true;
            this.searchBar.Size = new System.Drawing.Size(525, 41);
            this.searchBar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchBar.TabIndex = 1;
            this.searchBar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchBar.TextMarginBottom = 0;
            this.searchBar.TextMarginLeft = 10;
            this.searchBar.TextMarginTop = 1;
            this.searchBar.TextPlaceholder = "Search Societies";
            this.searchBar.UseSystemPasswordChar = false;
            this.searchBar.WordWrap = true;
            // 
            // EventsPage
            // 
            this.EventsPage.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.EventsPage.Location = new System.Drawing.Point(4, 4);
            this.EventsPage.Name = "EventsPage";
            this.EventsPage.Padding = new System.Windows.Forms.Padding(3);
            this.EventsPage.Size = new System.Drawing.Size(1071, 703);
            this.EventsPage.TabIndex = 1;
            this.EventsPage.Text = "Events";
            // 
            // societyReg
            // 
            this.societyReg.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.societyReg.Controls.Add(this.uploadImageBtn);
            this.societyReg.Controls.Add(this.uploadImgPicBox);
            this.societyReg.Controls.Add(this.availableMentors);
            this.societyReg.Controls.Add(this.societyDesc);
            this.societyReg.Controls.Add(this.societySlogan);
            this.societyReg.Controls.Add(this.societyName);
            this.societyReg.Controls.Add(this.regNewSociety);
            this.societyReg.Controls.Add(this.label6);
            this.societyReg.Controls.Add(this.label5);
            this.societyReg.Controls.Add(this.label4);
            this.societyReg.Controls.Add(this.label3);
            this.societyReg.Controls.Add(this.label2);
            this.societyReg.Controls.Add(this.sName);
            this.societyReg.Location = new System.Drawing.Point(4, 4);
            this.societyReg.Name = "societyReg";
            this.societyReg.Padding = new System.Windows.Forms.Padding(3);
            this.societyReg.Size = new System.Drawing.Size(1071, 703);
            this.societyReg.TabIndex = 2;
            this.societyReg.Text = "Register a New Society !!";
            // 
            // uploadImageBtn
            // 
            this.uploadImageBtn.AllowAnimations = true;
            this.uploadImageBtn.AllowMouseEffects = true;
            this.uploadImageBtn.AllowToggling = true;
            this.uploadImageBtn.AnimationSpeed = 200;
            this.uploadImageBtn.AutoGenerateColors = false;
            this.uploadImageBtn.AutoRoundBorders = false;
            this.uploadImageBtn.AutoSizeLeftIcon = true;
            this.uploadImageBtn.AutoSizeRightIcon = true;
            this.uploadImageBtn.BackColor = System.Drawing.Color.Transparent;
            this.uploadImageBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.uploadImageBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("uploadImageBtn.BackgroundImage")));
            this.uploadImageBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadImageBtn.ButtonText = "Upload Image";
            this.uploadImageBtn.ButtonTextMarginLeft = 0;
            this.uploadImageBtn.ColorContrastOnClick = 45;
            this.uploadImageBtn.ColorContrastOnHover = 45;
            this.uploadImageBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.uploadImageBtn.CustomizableEdges = borderEdges4;
            this.uploadImageBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.uploadImageBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.uploadImageBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.uploadImageBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.uploadImageBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.uploadImageBtn.Font = new System.Drawing.Font("Verdana", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.uploadImageBtn.ForeColor = System.Drawing.Color.White;
            this.uploadImageBtn.IconLeft = null;
            this.uploadImageBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.uploadImageBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.uploadImageBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.uploadImageBtn.IconMarginLeft = 11;
            this.uploadImageBtn.IconPadding = 10;
            this.uploadImageBtn.IconRight = null;
            this.uploadImageBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.uploadImageBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.uploadImageBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.uploadImageBtn.IconSize = 25;
            this.uploadImageBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.uploadImageBtn.IdleBorderRadius = 0;
            this.uploadImageBtn.IdleBorderThickness = 0;
            this.uploadImageBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.uploadImageBtn.IdleIconLeftImage = null;
            this.uploadImageBtn.IdleIconRightImage = null;
            this.uploadImageBtn.IndicateFocus = true;
            this.uploadImageBtn.Location = new System.Drawing.Point(710, 188);
            this.uploadImageBtn.Margin = new System.Windows.Forms.Padding(5);
            this.uploadImageBtn.Name = "uploadImageBtn";
            this.uploadImageBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.uploadImageBtn.OnDisabledState.BorderRadius = 39;
            this.uploadImageBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadImageBtn.OnDisabledState.BorderThickness = 1;
            this.uploadImageBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.uploadImageBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.uploadImageBtn.OnDisabledState.IconLeftImage = null;
            this.uploadImageBtn.OnDisabledState.IconRightImage = null;
            this.uploadImageBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.uploadImageBtn.onHoverState.BorderRadius = 39;
            this.uploadImageBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.uploadImageBtn.onHoverState.BorderThickness = 1;
            this.uploadImageBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.uploadImageBtn.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.uploadImageBtn.onHoverState.IconLeftImage = null;
            this.uploadImageBtn.onHoverState.IconRightImage = null;
            this.uploadImageBtn.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.uploadImageBtn.OnIdleState.BorderRadius = 39;
            this.uploadImageBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadImageBtn.OnIdleState.BorderThickness = 1;
            this.uploadImageBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.uploadImageBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.uploadImageBtn.OnIdleState.IconLeftImage = null;
            this.uploadImageBtn.OnIdleState.IconRightImage = null;
            this.uploadImageBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.uploadImageBtn.OnPressedState.BorderRadius = 39;
            this.uploadImageBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadImageBtn.OnPressedState.BorderThickness = 1;
            this.uploadImageBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.uploadImageBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.uploadImageBtn.OnPressedState.IconLeftImage = null;
            this.uploadImageBtn.OnPressedState.IconRightImage = null;
            this.uploadImageBtn.Size = new System.Drawing.Size(128, 38);
            this.uploadImageBtn.TabIndex = 18;
            this.uploadImageBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.uploadImageBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.uploadImageBtn.TextMarginLeft = 0;
            this.uploadImageBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.uploadImageBtn.UseDefaultRadiusAndThickness = true;
            this.uploadImageBtn.Click += new System.EventHandler(this.uploadImageBtn_Click);
            // 
            // uploadImgPicBox
            // 
            this.uploadImgPicBox.AllowFocused = false;
            this.uploadImgPicBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.uploadImgPicBox.AutoSizeHeight = true;
            this.uploadImgPicBox.BorderRadius = 61;
            this.uploadImgPicBox.Image = ((System.Drawing.Image)(resources.GetObject("uploadImgPicBox.Image")));
            this.uploadImgPicBox.IsCircle = true;
            this.uploadImgPicBox.Location = new System.Drawing.Point(865, 127);
            this.uploadImgPicBox.Name = "uploadImgPicBox";
            this.uploadImgPicBox.Size = new System.Drawing.Size(123, 123);
            this.uploadImgPicBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.uploadImgPicBox.TabIndex = 17;
            this.uploadImgPicBox.TabStop = false;
            this.uploadImgPicBox.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // availableMentors
            // 
            this.availableMentors.BackColor = System.Drawing.Color.Transparent;
            this.availableMentors.BackgroundColor = System.Drawing.Color.White;
            this.availableMentors.BorderColor = System.Drawing.Color.Silver;
            this.availableMentors.BorderRadius = 1;
            this.availableMentors.Color = System.Drawing.Color.Silver;
            this.availableMentors.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.availableMentors.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.availableMentors.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.availableMentors.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.availableMentors.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.availableMentors.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.availableMentors.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.availableMentors.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.availableMentors.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.availableMentors.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.availableMentors.FillDropDown = true;
            this.availableMentors.FillIndicator = false;
            this.availableMentors.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.availableMentors.Font = new System.Drawing.Font("Verdana", 9.75F);
            this.availableMentors.ForeColor = System.Drawing.Color.Black;
            this.availableMentors.FormattingEnabled = true;
            this.availableMentors.Icon = null;
            this.availableMentors.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.availableMentors.IndicatorColor = System.Drawing.Color.DarkGray;
            this.availableMentors.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.availableMentors.IndicatorThickness = 2;
            this.availableMentors.IsDropdownOpened = false;
            this.availableMentors.ItemBackColor = System.Drawing.Color.White;
            this.availableMentors.ItemBorderColor = System.Drawing.Color.White;
            this.availableMentors.ItemForeColor = System.Drawing.Color.Black;
            this.availableMentors.ItemHeight = 26;
            this.availableMentors.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.availableMentors.ItemHighLightForeColor = System.Drawing.Color.White;
            this.availableMentors.ItemTopMargin = 3;
            this.availableMentors.Location = new System.Drawing.Point(339, 460);
            this.availableMentors.Name = "availableMentors";
            this.availableMentors.Size = new System.Drawing.Size(260, 32);
            this.availableMentors.TabIndex = 16;
            this.availableMentors.Text = null;
            this.availableMentors.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.availableMentors.TextLeftMargin = 5;
            // 
            // societyDesc
            // 
            this.societyDesc.AcceptsReturn = false;
            this.societyDesc.AcceptsTab = false;
            this.societyDesc.AnimationSpeed = 200;
            this.societyDesc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.societyDesc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.societyDesc.AutoSizeHeight = true;
            this.societyDesc.BackColor = System.Drawing.Color.Transparent;
            this.societyDesc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("societyDesc.BackgroundImage")));
            this.societyDesc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.societyDesc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.societyDesc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.societyDesc.BorderColorIdle = System.Drawing.Color.Silver;
            this.societyDesc.BorderRadius = 30;
            this.societyDesc.BorderThickness = 1;
            this.societyDesc.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.societyDesc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.societyDesc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.societyDesc.DefaultFont = new System.Drawing.Font("Verdana", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.societyDesc.DefaultText = "";
            this.societyDesc.FillColor = System.Drawing.Color.White;
            this.societyDesc.HideSelection = true;
            this.societyDesc.IconLeft = null;
            this.societyDesc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.societyDesc.IconPadding = 10;
            this.societyDesc.IconRight = null;
            this.societyDesc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.societyDesc.Lines = new string[0];
            this.societyDesc.Location = new System.Drawing.Point(339, 277);
            this.societyDesc.MaximumSize = new System.Drawing.Size(260, 180);
            this.societyDesc.MaxLength = 32767;
            this.societyDesc.MinimumSize = new System.Drawing.Size(260, 100);
            this.societyDesc.Modified = false;
            this.societyDesc.Multiline = true;
            this.societyDesc.Name = "societyDesc";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyDesc.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.societyDesc.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyDesc.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyDesc.OnIdleState = stateProperties8;
            this.societyDesc.Padding = new System.Windows.Forms.Padding(3);
            this.societyDesc.PasswordChar = '\0';
            this.societyDesc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.societyDesc.PlaceholderText = "Data, Data, Data";
            this.societyDesc.ReadOnly = false;
            this.societyDesc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.societyDesc.SelectedText = "";
            this.societyDesc.SelectionLength = 0;
            this.societyDesc.SelectionStart = 0;
            this.societyDesc.ShortcutsEnabled = true;
            this.societyDesc.Size = new System.Drawing.Size(260, 139);
            this.societyDesc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.societyDesc.TabIndex = 15;
            this.societyDesc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.societyDesc.TextMarginBottom = 0;
            this.societyDesc.TextMarginLeft = 10;
            this.societyDesc.TextMarginTop = 10;
            this.societyDesc.TextPlaceholder = "Data, Data, Data";
            this.societyDesc.UseSystemPasswordChar = false;
            this.societyDesc.WordWrap = true;
            // 
            // societySlogan
            // 
            this.societySlogan.AcceptsReturn = false;
            this.societySlogan.AcceptsTab = false;
            this.societySlogan.AnimationSpeed = 200;
            this.societySlogan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.societySlogan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.societySlogan.AutoSizeHeight = true;
            this.societySlogan.BackColor = System.Drawing.Color.Transparent;
            this.societySlogan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("societySlogan.BackgroundImage")));
            this.societySlogan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.societySlogan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.societySlogan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.societySlogan.BorderColorIdle = System.Drawing.Color.Silver;
            this.societySlogan.BorderRadius = 30;
            this.societySlogan.BorderThickness = 1;
            this.societySlogan.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.societySlogan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.societySlogan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.societySlogan.DefaultFont = new System.Drawing.Font("Verdana", 9.75F);
            this.societySlogan.DefaultText = "";
            this.societySlogan.FillColor = System.Drawing.Color.White;
            this.societySlogan.HideSelection = true;
            this.societySlogan.IconLeft = null;
            this.societySlogan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.societySlogan.IconPadding = 10;
            this.societySlogan.IconRight = null;
            this.societySlogan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.societySlogan.Lines = new string[0];
            this.societySlogan.Location = new System.Drawing.Point(339, 212);
            this.societySlogan.MaxLength = 32767;
            this.societySlogan.MinimumSize = new System.Drawing.Size(1, 1);
            this.societySlogan.Modified = false;
            this.societySlogan.Multiline = false;
            this.societySlogan.Name = "societySlogan";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societySlogan.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.societySlogan.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societySlogan.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societySlogan.OnIdleState = stateProperties12;
            this.societySlogan.Padding = new System.Windows.Forms.Padding(3);
            this.societySlogan.PasswordChar = '\0';
            this.societySlogan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.societySlogan.PlaceholderText = "Data, Data, Data";
            this.societySlogan.ReadOnly = false;
            this.societySlogan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.societySlogan.SelectedText = "";
            this.societySlogan.SelectionLength = 0;
            this.societySlogan.SelectionStart = 0;
            this.societySlogan.ShortcutsEnabled = true;
            this.societySlogan.Size = new System.Drawing.Size(260, 38);
            this.societySlogan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.societySlogan.TabIndex = 14;
            this.societySlogan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.societySlogan.TextMarginBottom = 0;
            this.societySlogan.TextMarginLeft = 3;
            this.societySlogan.TextMarginTop = 1;
            this.societySlogan.TextPlaceholder = "Data, Data, Data";
            this.societySlogan.UseSystemPasswordChar = false;
            this.societySlogan.WordWrap = true;
            // 
            // societyName
            // 
            this.societyName.AcceptsReturn = false;
            this.societyName.AcceptsTab = false;
            this.societyName.AnimationSpeed = 200;
            this.societyName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.societyName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.societyName.AutoSizeHeight = true;
            this.societyName.BackColor = System.Drawing.Color.Transparent;
            this.societyName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("societyName.BackgroundImage")));
            this.societyName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.societyName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.societyName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.societyName.BorderColorIdle = System.Drawing.Color.Silver;
            this.societyName.BorderRadius = 30;
            this.societyName.BorderThickness = 1;
            this.societyName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.societyName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.societyName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.societyName.DefaultFont = new System.Drawing.Font("Verdana", 9.75F);
            this.societyName.DefaultText = "";
            this.societyName.FillColor = System.Drawing.Color.White;
            this.societyName.HideSelection = true;
            this.societyName.IconLeft = null;
            this.societyName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.societyName.IconPadding = 10;
            this.societyName.IconRight = null;
            this.societyName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.societyName.Lines = new string[0];
            this.societyName.Location = new System.Drawing.Point(334, 151);
            this.societyName.MaxLength = 32767;
            this.societyName.MinimumSize = new System.Drawing.Size(1, 1);
            this.societyName.Modified = false;
            this.societyName.Multiline = false;
            this.societyName.Name = "societyName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.societyName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.societyName.OnIdleState = stateProperties16;
            this.societyName.Padding = new System.Windows.Forms.Padding(3);
            this.societyName.PasswordChar = '\0';
            this.societyName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.societyName.PlaceholderText = "Fast Data Science Society";
            this.societyName.ReadOnly = false;
            this.societyName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.societyName.SelectedText = "";
            this.societyName.SelectionLength = 0;
            this.societyName.SelectionStart = 0;
            this.societyName.ShortcutsEnabled = true;
            this.societyName.Size = new System.Drawing.Size(260, 38);
            this.societyName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.societyName.TabIndex = 13;
            this.societyName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.societyName.TextMarginBottom = 0;
            this.societyName.TextMarginLeft = 3;
            this.societyName.TextMarginTop = 1;
            this.societyName.TextPlaceholder = "Fast Data Science Society";
            this.societyName.UseSystemPasswordChar = false;
            this.societyName.WordWrap = true;
            // 
            // regNewSociety
            // 
            this.regNewSociety.AllowAnimations = true;
            this.regNewSociety.AllowMouseEffects = true;
            this.regNewSociety.AllowToggling = true;
            this.regNewSociety.AnimationSpeed = 200;
            this.regNewSociety.AutoGenerateColors = false;
            this.regNewSociety.AutoRoundBorders = false;
            this.regNewSociety.AutoSizeLeftIcon = true;
            this.regNewSociety.AutoSizeRightIcon = true;
            this.regNewSociety.BackColor = System.Drawing.Color.Transparent;
            this.regNewSociety.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.regNewSociety.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("regNewSociety.BackgroundImage")));
            this.regNewSociety.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.regNewSociety.ButtonText = "Register";
            this.regNewSociety.ButtonTextMarginLeft = 0;
            this.regNewSociety.ColorContrastOnClick = 45;
            this.regNewSociety.ColorContrastOnHover = 45;
            this.regNewSociety.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.regNewSociety.CustomizableEdges = borderEdges5;
            this.regNewSociety.DialogResult = System.Windows.Forms.DialogResult.None;
            this.regNewSociety.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.regNewSociety.DisabledFillColor = System.Drawing.Color.Empty;
            this.regNewSociety.DisabledForecolor = System.Drawing.Color.Empty;
            this.regNewSociety.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.regNewSociety.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.regNewSociety.ForeColor = System.Drawing.Color.White;
            this.regNewSociety.IconLeft = null;
            this.regNewSociety.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.regNewSociety.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.regNewSociety.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.regNewSociety.IconMarginLeft = 11;
            this.regNewSociety.IconPadding = 10;
            this.regNewSociety.IconRight = null;
            this.regNewSociety.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.regNewSociety.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.regNewSociety.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.regNewSociety.IconSize = 25;
            this.regNewSociety.IdleBorderColor = System.Drawing.Color.Empty;
            this.regNewSociety.IdleBorderRadius = 0;
            this.regNewSociety.IdleBorderThickness = 0;
            this.regNewSociety.IdleFillColor = System.Drawing.Color.Empty;
            this.regNewSociety.IdleIconLeftImage = null;
            this.regNewSociety.IdleIconRightImage = null;
            this.regNewSociety.IndicateFocus = true;
            this.regNewSociety.Location = new System.Drawing.Point(359, 529);
            this.regNewSociety.Margin = new System.Windows.Forms.Padding(5);
            this.regNewSociety.Name = "regNewSociety";
            this.regNewSociety.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.regNewSociety.OnDisabledState.BorderRadius = 39;
            this.regNewSociety.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.regNewSociety.OnDisabledState.BorderThickness = 1;
            this.regNewSociety.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.regNewSociety.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.regNewSociety.OnDisabledState.IconLeftImage = null;
            this.regNewSociety.OnDisabledState.IconRightImage = null;
            this.regNewSociety.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.regNewSociety.onHoverState.BorderRadius = 39;
            this.regNewSociety.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.regNewSociety.onHoverState.BorderThickness = 1;
            this.regNewSociety.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.regNewSociety.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.regNewSociety.onHoverState.IconLeftImage = null;
            this.regNewSociety.onHoverState.IconRightImage = null;
            this.regNewSociety.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.regNewSociety.OnIdleState.BorderRadius = 39;
            this.regNewSociety.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.regNewSociety.OnIdleState.BorderThickness = 1;
            this.regNewSociety.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.regNewSociety.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.regNewSociety.OnIdleState.IconLeftImage = null;
            this.regNewSociety.OnIdleState.IconRightImage = null;
            this.regNewSociety.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.regNewSociety.OnPressedState.BorderRadius = 39;
            this.regNewSociety.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.regNewSociety.OnPressedState.BorderThickness = 1;
            this.regNewSociety.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(40)))), ((int)(((byte)(70)))));
            this.regNewSociety.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.regNewSociety.OnPressedState.IconLeftImage = null;
            this.regNewSociety.OnPressedState.IconRightImage = null;
            this.regNewSociety.Size = new System.Drawing.Size(220, 50);
            this.regNewSociety.TabIndex = 12;
            this.regNewSociety.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.regNewSociety.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.regNewSociety.TextMarginLeft = 0;
            this.regNewSociety.TextPadding = new System.Windows.Forms.Padding(0);
            this.regNewSociety.UseDefaultRadiusAndThickness = true;
            this.regNewSociety.Click += new System.EventHandler(this.regNewSociety_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(714, 153);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(120, 24);
            this.label6.TabIndex = 11;
            this.label6.Text = "Insert Logo:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(87, 457);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(155, 24);
            this.label5.TabIndex = 10;
            this.label5.Text = "Society Mentor:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(87, 277);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(195, 24);
            this.label4.TabIndex = 9;
            this.label4.Text = "Society Description:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(87, 212);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(155, 24);
            this.label3.TabIndex = 8;
            this.label3.Text = "Society Slogan:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(367, 57);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(286, 29);
            this.label2.TabIndex = 7;
            this.label2.Text = "Register a New Society";
            // 
            // sName
            // 
            this.sName.AutoSize = true;
            this.sName.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sName.ForeColor = System.Drawing.Color.White;
            this.sName.Location = new System.Drawing.Point(87, 151);
            this.sName.Name = "sName";
            this.sName.Size = new System.Drawing.Size(145, 24);
            this.sName.TabIndex = 6;
            this.sName.Text = "Society Name:";
            // 
            // Student
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1350, 729);
            this.Controls.Add(this.StudentPages);
            this.Controls.Add(this.panel1);
            this.Name = "Student";
            this.Text = "Student";
            this.Load += new System.EventHandler(this.Student_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.StudentPages.ResumeLayout(false);
            this.SocietiesPage.ResumeLayout(false);
            this.SocietiesPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.userPic)).EndInit();
            this.societyReg.ResumeLayout(false);
            this.societyReg.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uploadImgPicBox)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton societiesBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton eventsBtn;
        private Bunifu.UI.WinForms.BunifuPages StudentPages;
        private System.Windows.Forms.TabPage SocietiesPage;
        private System.Windows.Forms.TabPage EventsPage;
        private Bunifu.UI.WinForms.BunifuTextBox searchBar;
        private Bunifu.UI.WinForms.BunifuLabel userName;
        private Bunifu.UI.WinForms.BunifuPictureBox userPic;
        private System.Windows.Forms.FlowLayoutPanel societyCardsPanel;
        private System.Windows.Forms.TabPage societyReg;
        private System.Windows.Forms.Label sName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton regNewSociety;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton rSocietyForm;
        private Bunifu.UI.WinForms.BunifuTextBox societySlogan;
        private Bunifu.UI.WinForms.BunifuTextBox societyName;
        private Bunifu.UI.WinForms.BunifuTextBox societyDesc;
        private Bunifu.UI.WinForms.BunifuDropdown availableMentors;
        private Bunifu.UI.WinForms.BunifuPictureBox uploadImgPicBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton uploadImageBtn;
    }
}